trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_WORKING_DIR: 'infra'  # adjust if your .tf files are elsewhere

stages:
- stage: Terraform_Deploy
  jobs:
  - job: Deploy
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(TF_WORKING_DIR)'
        backendServiceArm: 'tmp15'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(TF_WORKING_DIR)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(TF_WORKING_DIR)'
        environmentServiceNameAzureRM: 'tmp15'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(TF_WORKING_DIR)'
        environmentServiceNameAzureRM: 'tmp15'
        ensureBackend: true
        allowTelemetryCollection: false
        runAzLogin: true
