trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

stages:
- stage: DeployInfra
  jobs:
  - job: CreateRGandVNet
    steps:

    - task: AzurePowerShell@5
      displayName: 'Create RG and VNet with /29'
      inputs:
        azureSubscription: 'tmp15'  # ✅ Verified service connection
        ScriptType: 'InlineScript'
        Inline: |
          $rgName = "x"
          $location = "East US"  # Change if needed
          $vnetName = "x-vnet"
          $addressPrefix = "10.0.0.0/29"

          Write-Host "Creating resource group: $rgName"
          New-AzResourceGroup -Name $rgName -Location $location

          Write-Host "Creating virtual network: $vnetName with address space $addressPrefix"
          New-AzVirtualNetwork -Name $vnetName `
            -ResourceGroupName $rgName `
            -Location $location `
            -AddressPrefix $addressPrefix
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
